config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :statuses

      resources :users

      resources :furnitures
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "furnitures#index"
  resources :statuses
  resources :users
  resources :furnitures
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/statuses_controller.rb
class Api::V1::StatusesController < Api::V1::GraphitiController
  def index
    statuses = StatusResource.all(params)
    respond_with(statuses)
  end

  def show
    status = StatusResource.find(params)
    respond_with(status)
  end

  def create
    status = StatusResource.build(params)

    if status.save
      render jsonapi: status, status: :created
    else
      render jsonapi_errors: status
    end
  end

  def update
    status = StatusResource.find(params)

    if status.update_attributes
      render jsonapi: status
    else
      render jsonapi_errors: status
    end
  end

  def destroy
    status = StatusResource.find(params)

    if status.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: status
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[show edit update destroy]

  def index
    @q = Status.ransack(params[:q])
    @statuses = @q.result(distinct: true).includes(:furnitures).page(params[:page]).per(10)
  end

  def show
    @furniture = Furniture.new
  end

  def new
    @status = Status.new
  end

  def edit; end

  def create
    @status = Status.new(status_params)

    if @status.save
      redirect_to @status, notice: "Status was successfully created."
    else
      render :new
    end
  end

  def update
    if @status.update(status_params)
      redirect_to @status, notice: "Status was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @status.destroy
    redirect_to statuses_url, notice: "Status was successfully destroyed."
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:furniture_id)
  end
end

app/views/statuses/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Status #<%= status.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Furniture</dt>
      <dd><%= status.furniture_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back status, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_status_url(status), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to status, method: :delete, data: { confirm: "Do you really want to delete this status?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(status.updated_at) %> ago
  </div>
</div>

app/views/statuses/_form.html.erb
<% was_validated = status.errors.any? %>

<%= form_with(model: status, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% furniture_class = "form-control" %>
    <% furniture_was_invalid = status.errors.include?(:furniture) %>

    <% if was_validated %>
      <% if furniture_was_invalid %>
        <% furniture_class << " is-invalid" %>
      <% else %>
        <% furniture_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :furniture_id %>
    <%= f.number_field :furniture_id, class: furniture_class, placeholder: "Enter furniture" %>
    <% if furniture_was_invalid %>
      <% status.errors.full_messages_for(:furniture).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/statuses/_list_item.html.erb
<%= link_to status, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= status %>
    <small class="text-muted">
      <%= time_ago_in_words(status.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/statuses/_status_furnitures.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Furnitures

    <a data-toggle="collapse" href="#status_furnitures_new_form">
      Add furniture
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @status.furnitures.each do |furniture| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to furniture, furniture %>

        <%= link_to furniture, method: :delete, data: { confirm: "Do you really want to delete this furniture" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="status_furnitures_new_form">
        <%= render partial: "statuses/status_furnitures_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/statuses/_status_furnitures_new_form.html.erb
<%= form_with(model: @furniture, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>

    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :category, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>

    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :google_map %>

    <%= f.text_field :google_map, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :status_id, value: @status.id %>

  <%= f.submit "Create furniture", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/statuses/_statuses_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "statuses_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :furniture_id, "Furniture" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :furniture_id_gteq, :class => "form-control", :placeholder => "Furniture greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :furniture_id_lteq, :class => "form-control", :placeholder => "Furniture less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/statuses" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#statuses_filters">
  Show filters
</a>

app/views/statuses/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Status #<%= @status.id %>
      </h2>

      <div class="card-body">
        <%= render "form", status: @status %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/statuses/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Statuses

      <%= link_to new_status_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "statuses/statuses_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Statuses

        <%= link_to new_status_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @statuses, partial: "list_item", as: :status %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @statuses, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/statuses/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Status
      </h2>

      <div class="card-body">
        <%= render "form", status: @status %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/statuses/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @status, partial: "card", as: :status %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "statuses/status_furnitures" %>
  </div>
</div>