config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :statuses

      resources :users

      resources :furnitures
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "furnitures#index"
  resources :statuses
  resources :users
  resources :furnitures
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/furniture.rb
require "open-uri"
class Furniture < ApplicationRecord
  before_validation :geocode_google_map

  def geocode_google_map
    if google_map.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(google_map)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.google_map_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.google_map_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.google_map_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_base64_uploader :photo, PhotoUploader

  # Direct associations

  belongs_to :status

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    id
  end
end

app/controllers/api/v1/furnitures_controller.rb
class Api::V1::FurnituresController < Api::V1::GraphitiController
  def index
    furnitures = FurnitureResource.all(params)
    respond_with(furnitures)
  end

  def show
    furniture = FurnitureResource.find(params)
    respond_with(furniture)
  end

  def create
    furniture = FurnitureResource.build(params)

    if furniture.save
      render jsonapi: furniture, status: :created
    else
      render jsonapi_errors: furniture
    end
  end

  def update
    furniture = FurnitureResource.find(params)

    if furniture.update_attributes
      render jsonapi: furniture
    else
      render jsonapi_errors: furniture
    end
  end

  def destroy
    furniture = FurnitureResource.find(params)

    if furniture.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: furniture
    end
  end
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: %i[show edit update destroy]

  def index
    @q = Furniture.ransack(params[:q])
    @furnitures = @q.result(distinct: true).includes(:user,
                                                     :status).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@furnitures.where.not(google_map_latitude: nil)) do |furniture, marker|
      marker.lat furniture.google_map_latitude
      marker.lng furniture.google_map_longitude
    end
  end

  def show; end

  def new
    @furniture = Furniture.new
  end

  def edit; end

  def create
    @furniture = Furniture.new(furniture_params)

    if @furniture.save
      message = "Furniture was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @furniture, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @furniture.update(furniture_params)
      redirect_to @furniture, notice: "Furniture was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @furniture.destroy
    message = "Furniture was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to furnitures_url, notice: message
    end
  end

  private

  def set_furniture
    @furniture = Furniture.find(params[:id])
  end

  def furniture_params
    params.require(:furniture).permit(:title, :photo, :category, :price,
                                      :google_map, :user_id, :status_id)
  end
end

app/views/furnitures/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/furnitures/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Furniture #<%= furniture.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= furniture.title %></dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @furniture.photo, class: "img-fluid" %>
      </dd>

      <dt>Category</dt>
      <dd><%= furniture.category %></dd>

      <dt>Price</dt>
      <dd><%= furniture.price %></dd>

      <dt>Google map</dt>
      <dd>
        <div>
          <%= render partial: "furnitures/one_photo_map" %>
        </div>
      </dd>

      <dt>User</dt>
      <dd>
        <% if @furniture.user.present? %>
          <%= link_to furniture.user, furniture.user %>
        <% end %>
      </dd>

      <dt>Status</dt>
      <dd>
        <% if @furniture.status.present? %>
          <%= link_to furniture.status, furniture.status %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back furniture, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_furniture_url(furniture), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to furniture, method: :delete, data: { confirm: "Do you really want to delete this furniture?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(furniture.updated_at) %> ago
  </div>
</div>

app/views/furnitures/_form.html.erb
<% was_validated = furniture.errors.any? %>

<%= form_with(model: furniture, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = furniture.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_area :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% furniture.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_class = "form-control" %>
    <% photo_was_invalid = furniture.errors.include?(:photo) %>

    <% if was_validated %>
      <% if photo_was_invalid %>
        <% photo_class << " is-invalid" %>
      <% else %>
        <% photo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <% if photo_was_invalid %>
      <% furniture.errors.full_messages_for(:photo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = furniture.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category %>
    <%= f.text_area :category, class: category_class, placeholder: "Enter category" %>
    <% if category_was_invalid %>
      <% furniture.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% price_class = "form-control" %>
    <% price_was_invalid = furniture.errors.include?(:price) %>

    <% if was_validated %>
      <% if price_was_invalid %>
        <% price_class << " is-invalid" %>
      <% else %>
        <% price_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :price %>
    <%= f.text_field :price, class: price_class, placeholder: "Enter price" %>
    <% if price_was_invalid %>
      <% furniture.errors.full_messages_for(:price).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% google_map_class = "form-control" %>
    <% google_map_was_invalid = furniture.errors.include?(:google_map) %>

    <% if was_validated %>
      <% if google_map_was_invalid %>
        <% google_map_class << " is-invalid" %>
      <% else %>
        <% google_map_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :google_map %>
    <%= f.text_field :google_map, class: google_map_class, placeholder: "Enter google map" %>
    <% if google_map_was_invalid %>
      <% furniture.errors.full_messages_for(:google_map).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = furniture.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% furniture.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = furniture.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status_id %>
    <%= f.collection_select :status_id, Status.all, :id, :to_s, {}, class: "form-control" %>
    <% if status_was_invalid %>
      <% furniture.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/furnitures/_furnitures_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "furnitures_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :price, "Price" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :price_gteq, :class => "form-control", :placeholder => "Price greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :price_lteq, :class => "form-control", :placeholder => "Price less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category_cont, "Category contains" %>
    <%= f.text_field :category_cont, :class => "form-control", :placeholder => "Category contains" %>
  </div>

  <div class="form-group">
    <%= f.label :title_cont, "Title contains" %>
    <%= f.text_field :title_cont, :class => "form-control", :placeholder => "Title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :furniture_id, "Status Furniture" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :status_furniture_id_gteq, :class => "form-control", :placeholder => "Status Furniture greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :status_furniture_id_lteq, :class => "form-control", :placeholder => "Status Furniture less than or equal to" %>
      </div>
    </div>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/furnitures" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#furnitures_filters">
  Show filters
</a>

app/views/furnitures/_list_item.html.erb
<%= link_to furniture, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= furniture %>
    <small class="text-muted">
      <%= time_ago_in_words(furniture.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/furnitures/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @furniture.google_map_latitude %>,
        "lng": <%= @furniture.google_map_longitude %>,
        "infowindow": "<h5><%= @furniture.created_at %></h5><small><%= @furniture.google_map_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/furnitures/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Furniture #<%= @furniture.id %>
      </h2>

      <div class="card-body">
        <%= render "form", furniture: @furniture %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Furnitures

      <%= link_to new_furniture_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "furnitures/furnitures_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "furnitures/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Furnitures

        <%= link_to new_furniture_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @furnitures, partial: "list_item", as: :furniture %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @furnitures, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/furnitures/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Furniture
      </h2>

      <div class="card-body">
        <%= render "form", furniture: @furniture %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @furniture, partial: "card", as: :furniture %>
  </div>
</div>